// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.3
// source: err_code.proto

package err_code

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_SUCCESS ErrCode = 0
	// 系统类
	ErrCode_ErrSystem   ErrCode = 1000
	ErrCode_ErrValidate ErrCode = 1001 // 参数校验不通过
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "SUCCESS",
		1000: "ErrSystem",
		1001: "ErrValidate",
	}
	ErrCode_value = map[string]int32{
		"SUCCESS":     0,
		"ErrSystem":   1000,
		"ErrValidate": 1001,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_err_code_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_err_code_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_err_code_proto_rawDescGZIP(), []int{0}
}

var File_err_code_proto protoreflect.FileDescriptor

var file_err_code_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x38, 0x0a, 0x07, 0x45,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x10, 0xe8, 0x07, 0x12, 0x10, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x10, 0xe9, 0x07, 0x42, 0x2d, 0x5a, 0x2b, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x2d, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x72, 0x2d, 0x6b, 0x69, 0x74, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_err_code_proto_rawDescOnce sync.Once
	file_err_code_proto_rawDescData = file_err_code_proto_rawDesc
)

func file_err_code_proto_rawDescGZIP() []byte {
	file_err_code_proto_rawDescOnce.Do(func() {
		file_err_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_err_code_proto_rawDescData)
	})
	return file_err_code_proto_rawDescData
}

var file_err_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_err_code_proto_goTypes = []interface{}{
	(ErrCode)(0), // 0: errorCode.ErrCode
}
var file_err_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_err_code_proto_init() }
func file_err_code_proto_init() {
	if File_err_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_err_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_err_code_proto_goTypes,
		DependencyIndexes: file_err_code_proto_depIdxs,
		EnumInfos:         file_err_code_proto_enumTypes,
	}.Build()
	File_err_code_proto = out.File
	file_err_code_proto_rawDesc = nil
	file_err_code_proto_goTypes = nil
	file_err_code_proto_depIdxs = nil
}
