// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hanson/go-toolbox/utils"
	"github.com/hertz-contrib/cors"
	"hertz-starter-kit/biz/router/middleware"
	"hertz-starter-kit/config"
	"hertz-starter-kit/db"
	"log"
	"time"
)

func main() {
	// 配置
	utils.KeepNewDateLogFile()

	ctx := context.Background()
	ctx = context.WithValue(ctx, "trace_id", fmt.Sprintf("process_start_%d", time.Now().Unix()))

	config.LoadConfig()

	// db 操作
	err := db.InitDb(ctx)
	if err != nil {
		log.Printf("err: %+v", err)
		return
	}

	err = db.AutoMigrate(ctx)
	if err != nil {
		log.Printf("err: %+v", err)
		return
	}

	h := server.Default(
		server.WithAutoReloadRender(true, 0),
		server.WithHostPorts(":"+config.Cfg.Port),
	)

	h.Use(corsMiddleware())
	h.Use(middleware.LogTrace())
	h.Use(recovery.Recovery(recovery.WithRecoveryHandler(middleware.RecoveryHandler)))
	middleware.InitAdminJwt()
	register(h)
	h.Spin()
}

func corsMiddleware() app.HandlerFunc {
	return cors.New(cors.Config{
		AllowOrigins:     config.Cfg.AllowOrigins,
		AllowMethods:     []string{"POST", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization", "Trace-Id"},
		ExposeHeaders:    []string{"Content-Length", "Access-Control-Allow-Origin", "Access-Control-Allow-Headers", "Cache-Control", "Content-Language", "Content-Type"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	})
}
