// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.3
// source: paginate.proto

package paginate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultOrderBy int32

const (
	DefaultOrderBy_OrderByNil    DefaultOrderBy = 0
	DefaultOrderBy_OrderByIdAsc  DefaultOrderBy = 1
	DefaultOrderBy_OrderByIdDesc DefaultOrderBy = 2
)

// Enum value maps for DefaultOrderBy.
var (
	DefaultOrderBy_name = map[int32]string{
		0: "OrderByNil",
		1: "OrderByIdAsc",
		2: "OrderByIdDesc",
	}
	DefaultOrderBy_value = map[string]int32{
		"OrderByNil":    0,
		"OrderByIdAsc":  1,
		"OrderByIdDesc": 2,
	}
)

func (x DefaultOrderBy) Enum() *DefaultOrderBy {
	p := new(DefaultOrderBy)
	*p = x
	return p
}

func (x DefaultOrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultOrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_paginate_proto_enumTypes[0].Descriptor()
}

func (DefaultOrderBy) Type() protoreflect.EnumType {
	return &file_paginate_proto_enumTypes[0]
}

func (x DefaultOrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultOrderBy.Descriptor instead.
func (DefaultOrderBy) EnumDescriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{0}
}

type DefaultListOption int32

const (
	DefaultListOption_ListOptionNil     DefaultListOption = 0
	DefaultListOption_ListOptionIdList  DefaultListOption = 101
	DefaultListOption_ListOptionOrderBy DefaultListOption = 102
)

// Enum value maps for DefaultListOption.
var (
	DefaultListOption_name = map[int32]string{
		0:   "ListOptionNil",
		101: "ListOptionIdList",
		102: "ListOptionOrderBy",
	}
	DefaultListOption_value = map[string]int32{
		"ListOptionNil":     0,
		"ListOptionIdList":  101,
		"ListOptionOrderBy": 102,
	}
)

func (x DefaultListOption) Enum() *DefaultListOption {
	p := new(DefaultListOption)
	*p = x
	return p
}

func (x DefaultListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefaultListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_paginate_proto_enumTypes[1].Descriptor()
}

func (DefaultListOption) Type() protoreflect.EnumType {
	return &file_paginate_proto_enumTypes[1]
}

func (x DefaultListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefaultListOption.Descriptor instead.
func (DefaultListOption) EnumDescriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{1}
}

type Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty" form:"type" query:"type"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" form:"value" query:"value"`
}

func (x *Options) Reset() {
	*x = Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_paginate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Options) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 分页拉取机制
type ListOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @desc: 搜索过滤逻辑，不支持逻辑或
	//
	//	options内部是逻辑与关系，暂不支持逻辑或；尽量避免复杂的过滤逻辑，后台不好分页
	//
	// @ignore: all
	Options []*ListOption_Option `protobuf:"bytes,1,rep,name=options,proto3" json:"options" form:"options" query:"options"`
	// @desc: 需要获取的索引开始位置
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty" form:"offset" query:"offset"`
	// @desc: 分页的每页字段长度
	Limit     uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty" form:"limit" query:"limit"`
	NeedCount bool   `protobuf:"varint,4,opt,name=need_count,json=needCount,proto3" json:"need_count,omitempty" form:"need_count" query:"need_count"`
	// @desc: 需要获取的索引开始位置标记
	Cursor string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty" form:"cursor" query:"cursor"`
}

func (x *ListOption) Reset() {
	*x = ListOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOption) ProtoMessage() {}

func (x *ListOption) ProtoReflect() protoreflect.Message {
	mi := &file_paginate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOption.ProtoReflect.Descriptor instead.
func (*ListOption) Descriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{1}
}

func (x *ListOption) GetOptions() []*ListOption_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListOption) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListOption) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOption) GetNeedCount() bool {
	if x != nil {
		return x.NeedCount
	}
	return false
}

func (x *ListOption) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type Paginate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @desc: 当前获取到的第一个的索引位置
	Offset uint32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset" query:"offset"`
	// @desc: 每页结果数
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit" query:"limit"`
	// @desc: 总页数
	Total int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty" form:"total" query:"total"`
	// @desc: 下次索引开始位置标记,为空标示没有下一个了
	Cursor string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty" form:"cursor" query:"cursor"`
}

func (x *Paginate) Reset() {
	*x = Paginate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paginate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paginate) ProtoMessage() {}

func (x *Paginate) ProtoReflect() protoreflect.Message {
	mi := &file_paginate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paginate.ProtoReflect.Descriptor instead.
func (*Paginate) Descriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{2}
}

func (x *Paginate) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Paginate) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Paginate) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Paginate) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListOption_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @desc: 类型，各业务定义的type
	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty" form:"type" query:"type"`
	// @desc: 参数，只支持1个参数，参数实际类型和意义由type决定
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" form:"value" query:"value"`
}

func (x *ListOption_Option) Reset() {
	*x = ListOption_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paginate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOption_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOption_Option) ProtoMessage() {}

func (x *ListOption_Option) ProtoReflect() protoreflect.Message {
	mi := &file_paginate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOption_Option.ProtoReflect.Descriptor instead.
func (*ListOption_Option) Descriptor() ([]byte, []int) {
	return file_paginate_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListOption_Option) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListOption_Option) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_paginate_proto protoreflect.FileDescriptor

var file_paginate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0xdc, 0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x1a, 0x32, 0x0a, 0x06, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x66,
	0x0a, 0x08, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2a, 0x45, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x79, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x79, 0x49, 0x64, 0x41, 0x73, 0x63, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x44, 0x65, 0x73, 0x63, 0x10, 0x02, 0x2a, 0x53, 0x0a,
	0x11, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79,
	0x10, 0x66, 0x42, 0x2a, 0x5a, 0x28, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x5f,
	0x63, 0x68, 0x61, 0x74, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paginate_proto_rawDescOnce sync.Once
	file_paginate_proto_rawDescData = file_paginate_proto_rawDesc
)

func file_paginate_proto_rawDescGZIP() []byte {
	file_paginate_proto_rawDescOnce.Do(func() {
		file_paginate_proto_rawDescData = protoimpl.X.CompressGZIP(file_paginate_proto_rawDescData)
	})
	return file_paginate_proto_rawDescData
}

var file_paginate_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_paginate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paginate_proto_goTypes = []interface{}{
	(DefaultOrderBy)(0),       // 0: paginate.DefaultOrderBy
	(DefaultListOption)(0),    // 1: paginate.DefaultListOption
	(*Options)(nil),           // 2: paginate.Options
	(*ListOption)(nil),        // 3: paginate.ListOption
	(*Paginate)(nil),          // 4: paginate.Paginate
	(*ListOption_Option)(nil), // 5: paginate.ListOption.Option
}
var file_paginate_proto_depIdxs = []int32{
	5, // 0: paginate.ListOption.options:type_name -> paginate.ListOption.Option
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paginate_proto_init() }
func file_paginate_proto_init() {
	if File_paginate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paginate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paginate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paginate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paginate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paginate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOption_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paginate_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paginate_proto_goTypes,
		DependencyIndexes: file_paginate_proto_depIdxs,
		EnumInfos:         file_paginate_proto_enumTypes,
		MessageInfos:      file_paginate_proto_msgTypes,
	}.Build()
	File_paginate_proto = out.File
	file_paginate_proto_rawDesc = nil
	file_paginate_proto_goTypes = nil
	file_paginate_proto_depIdxs = nil
}
