package db

import (
	"aggregate_chat/biz/model/admin/advanced_send"
	"aggregate_chat/biz/model/admin/ai"
	"aggregate_chat/biz/model/admin/ai_agent"
	"aggregate_chat/biz/model/admin/ai_sns"
	"aggregate_chat/biz/model/admin/ai_tag"
	"aggregate_chat/biz/model/admin/customer_service"
	"aggregate_chat/biz/model/admin/fastest_send"
	"aggregate_chat/biz/model/admin/instance"
	"aggregate_chat/biz/model/admin/material"
	"aggregate_chat/biz/model/admin/moment"
	"aggregate_chat/biz/model/admin/plugin"
	"aggregate_chat/biz/model/admin/room_tag"
	"aggregate_chat/biz/model/admin/sensitive"
	"aggregate_chat/biz/model/admin/setting"
	"aggregate_chat/biz/model/admin/sidebar"
	"aggregate_chat/biz/model/admin/sop"
	"aggregate_chat/biz/model/admin/stat"
	"aggregate_chat/biz/model/admin/sys_log"
	"aggregate_chat/biz/model/admin/system_label"
	"aggregate_chat/biz/model/admin/token"
	"aggregate_chat/biz/model/admin/user"
	"aggregate_chat/biz/model/admin/welcome"
	"aggregate_chat/biz/model/admin/wework"
	"aggregate_chat/biz/model/aggregate/arch"
	"aggregate_chat/biz/model/aggregate/base"
	"aggregate_chat/biz/model/aggregate/contact"
	"aggregate_chat/biz/model/aggregate/conversation"
	"aggregate_chat/biz/model/aggregate/label"
	"aggregate_chat/biz/model/aggregate/msg"
	"aggregate_chat/biz/model/aggregate/notification"
	"aggregate_chat/biz/model/aggregate/room"
	"aggregate_chat/biz/model/aggregate/wework_user"
	"aggregate_chat/biz/model/common/migration"
	"aggregate_chat/biz/model/custom/helper"
	"aggregate_chat/biz/model/open"
	"aggregate_chat/biz/model/task/add_contact"
	"aggregate_chat/biz/model/task/create_room"
	"aggregate_chat/biz/model/task/forward"
	"aggregate_chat/biz/model/wechat/sns"
	"aggregate_chat/biz/model/wechat/wechat_contact"
	"aggregate_chat/biz/model/wechat/wechat_msg"
	"aggregate_chat/biz/model/wechat/wechat_room"
	"aggregate_chat/biz/model/wechat/wechat_user"
	"aggregate_chat/utils/log"
	"context"
)

func AutoMigrate(ctx context.Context) error {
	m := &MyMigrator{}
	m.DB = Db
	m.Migrator.Migrator.Dialector = Db.Dialector
	err := m.AutoMigrate(
		&instance.ModelInstance{},
		&instance.ModelInstanceGroup{},
		&instance.ModelInstanceGroupMap{},
		&wework_user.ModelWeworkUser{},
		&customer_service.ModelCustomerService{},
		&customer_service.ModelCustomerServiceWeworkUser{},
		&msg.ModelMsg{},
		&contact.ModelContact{},
		&room.ModelRoom{},
		&conversation.ModelConversation{},
		&room.ModelRoomMember{},
		&msg.ModelSendRecord{},
		&wework_user.ModelCorp{},
		&sidebar.ModelSidebar{},
		&plugin.ModelPlugin{},
		&wework_user.ModelWeworkUserSeq{},
		&base.ModelRequestLog{},
		&conversation.ModelPinnedConversation{},
		&conversation.ModelPinnedConversation{},
		&material.ModelMaterial{},
		&material.ModelMaterialCategory{},
		&material.ModelMiniProgramRecord{},
		&setting.ModelSetting{},
		&sensitive.ModelSensitiveWord{},
		&notification.ModelNotification{},
		&conversation.ModelNoDisturbConversation{},
		&welcome.ModelWelcomeContactRule{},
		&welcome.ModelWelcomeContactRuleUin{},
		&moment.ModelMomentTask{},
		&moment.ModelMomentTaskUin{},
		&user.ModelUser{},
		&user.ModelUserMenu{},
		&setting.ModelGuidCallback{},
		&label.ModelLabel{},
		&label.ModelContactLabel{},
		&label.ModelLabelAiToken{},
		&label.ModelAutoLabel{},
		&advanced_send.ModelAdvancedSend{},
		&advanced_send.ModelAdvancedSendRecord{},
		&fastest_send.ModelFastestSend{},
		&conversation.ModelAssignConversation{},
		&conversation.ModelAssignConversationRecord{},
		&sop.ModelSopRule{},
		&sop.ModelSopRuleDay{},
		&sop.ModelSopRuleUser{},
		&arch.ModelInternalDepartment{},
		&arch.ModelInternalMember{},
		&ai_agent.ModelAiAgent{},
		&ai_agent.ModelAiReplyRule{},
		&ai_agent.ModelAiReplyRuleUser{},
		&migration.ModelMigration{},
		&room.ModelRoomTopMsg{},
		&wechat_user.ModelWechatUser{},
		&wechat_user.ModelWechatUserSeq{},
		&wechat_msg.ModelWechatMsg{},
		&wechat_contact.ModelWechatContact{},
		&wechat_room.ModelWechatRoom{},
		&wechat_room.ModelWechatRoomMember{},
		&system_label.ModelSystemLabel{},
		&room_tag.ModelRoomTag{},
		&room_tag.ModelRoomTagMap{},
		&wechat_contact.ModelWechatLabel{},
		&create_room.ModelRoomCreateTask{},
		&add_contact.ModelAddContactTask{},
		&add_contact.ModelAddContactRecord{},
		&token.ModelTokenUserSetting{},
		&token.ModelTokenUseRecord{},
		&token.ModelTokenUserWallet{},
		&ai.ModelAiConversation{},
		&stat.ModelStat{},
		&stat.ModelStatLabel{},
		&stat.ModelStatFeishuConfig{},
		&conversation.ModelAssignConversationHistory{},
		&material.ModelMaterialWecomFinder{},
		&wechat_contact.ModelWechatContactLabel{},
		&ai_tag.ModelAiTagCorpSetting{},
		&ai_tag.ModelAiTagResult{},
		&open.ModelOpenChannel{},
		&open.ModelOpenApp{},
		&open.ModelOpenAppAuthorizeGuid{},
		&open.ModelOpenTestSend{},
		&sns.ModelSns{},
		&sns.ModelSnsProcessed{},
		&ai_sns.ModelAiSnsSetting{},
		&ai_sns.ModelAiSnsUserSetting{},
		&helper.ModelHelperRoom{},
		&sys_log.ModelSysLog{},
		&wework.ModelWeworkCorp{},
		&forward.ModelAutoForwardTask{},
		//&contact.ModelWechatContact{},
		//&room.ModelWechatRoom{},
		//&room.ModelWechatRoomMember{},
		//&xzs.ModelXzsRoom{},
		//&xzs.ModelXzsContactRoom{},
	)
	if err != nil {
		log.Errorf(ctx, "err: %+v", err)
		return err
	}

	return nil
}
